// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ComprehensiveSearch: typeof import('./src/components/ComprehensiveSearch/index.vue')['default']
    ExpertItem: typeof import('./src/components/ExpertItem/index.vue')['default']
    Footer: typeof import('./src/components/Footer/index.vue')['default']
    HomeTitle: typeof import('./src/components/HomeTitle/index.vue')['default']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    MobileConsole: typeof import('./src/components/MobileConsole/index.vue')['default']
    OverviewItem: typeof import('./src/components/OverviewItem/index.vue')['default']
    OverviewSearch: typeof import('./src/components/OverviewSearch/index.vue')['default']
    PptItem: typeof import('./src/components/PptItem/index.vue')['default']
    PreviewPdf: typeof import('./src/components/PptItem/previewPdf.vue')['default']
    ReportItem: typeof import('./src/components/ReportItem/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search/index.vue')['default']
    SearchTitle: typeof import('./src/components/ComprehensiveSearch/components/SearchTitle.vue')['default']
    Swiper: typeof import('./src/components/Swiper/index.vue')['default']
    Tabbar: typeof import('./src/components/Layout/Tabbar.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanList: typeof import('vant/es')['List']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanSearch: typeof import('vant/es')['Search']
    VanSpace: typeof import('vant/es')['Space']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
